spring:
  mvc:
    problemdetails:
      enabled: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    datasource-query-logger: INFO
    org.springframework.data: DEBUG